CREATE TABLE IF NOT EXISTS "companies" (
"CompanyName" TEXT,
  "CompanyNumber" TEXT PRIMARY KEY,
  "RegAddressCareOf" TEXT,
  "RegAddressPOBox" TEXT,
  "RegAddressAddressLine1" TEXT,
  "RegAddressAddressLine2" TEXT,
  "RegAddressPostTown" TEXT,
  "RegAddressCounty" TEXT,
  "RegAddressCountry" TEXT,
  "RegAddressPostCode" TEXT,
  "CompanyCategory" TEXT,
  "CompanyStatus" TEXT,
  "CountryOfOrigin" TEXT,
  "DissolutionDate" REAL,
  "IncorporationDate" TEXT,
  "AccountsAccountRefDay" REAL,
  "AccountsAccountRefMonth" REAL,
  "AccountsNextDueDate" TEXT,
  "AccountsLastMadeUpDate" TEXT,
  "AccountsAccountCategory" TEXT,
  "ReturnsNextDueDate" TEXT,
  "ReturnsLastMadeUpDate" TEXT,
  "MortgagesNumMortCharges" INTEGER,
  "MortgagesNumMortOutstanding" INTEGER,
  "MortgagesNumMortPartSatisfied" INTEGER,
  "MortgagesNumMortSatisfied" INTEGER,
  "SICCodeSicText_1" TEXT,
  "SICCodeSicText_2" TEXT,
  "SICCodeSicText_3" TEXT,
  "SICCodeSicText_4" TEXT,
  "LimitedPartnershipsNumGenPartners" INTEGER,
  "LimitedPartnershipsNumLimPartners" INTEGER,
  "URI" TEXT,
  "PreviousName_1CONDATE" TEXT,
  "PreviousName_1CompanyName" TEXT,
  "PreviousName_2CONDATE" TEXT,
  "PreviousName_2CompanyName" TEXT,
  "PreviousName_3CONDATE" TEXT,
  "PreviousName_3CompanyName" TEXT,
  "PreviousName_4CONDATE" TEXT,
  "PreviousName_4CompanyName" TEXT,
  "PreviousName_5CONDATE" TEXT,
  "PreviousName_5CompanyName" TEXT,
  "PreviousName_6CONDATE" TEXT,
  "PreviousName_6CompanyName" TEXT,
  "PreviousName_7CONDATE" TEXT,
  "PreviousName_7CompanyName" TEXT,
  "PreviousName_8CONDATE" TEXT,
  "PreviousName_8CompanyName" TEXT,
  "PreviousName_9CONDATE" TEXT,
  "PreviousName_9CompanyName" TEXT,
  "PreviousName_10CONDATE" TEXT,
  "PreviousName_10CompanyName" TEXT,
  "ConfStmtNextDueDate" TEXT,
  "ConfStmtLastMadeUpDate" TEXT
);
CREATE INDEX idx_company_status ON companies (CompanyStatus);
CREATE INDEX idx_accounts_category ON companies (AccountsAccountCategory);
CREATE INDEX idx_reg_address_county ON companies (UPPER(RegAddressCounty));
CREATE INDEX idx_accounts_due_date ON companies (AccountsNextDueDate);
CREATE INDEX idx_sic_code_1 ON companies (SICCodeSicText_1);
CREATE INDEX idx_sic_code_2 ON companies (SICCodeSicText_2);
CREATE INDEX idx_sic_code_3 ON companies (SICCodeSicText_3);
CREATE INDEX idx_sic_code_4 ON companies (SICCodeSicText_4);